# Generated by Django 4.0.3 on 2022-04-12 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_tag_note_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='tag',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
